### DISCUSSION TITLE
Input styling to match VitePress?

### DISCUSSION THREAD

**Discussion by ms264556** [pearmini/genji#208] [Q&A]
How should I be styling the Input controls when I'm using this with VitePress?

Buttons etc. don't currently pick up the standard VitePress styling. I can add global css, but is this the recommended solution?

e.g. in my theme/style/custom.css I added the following (which seems to work OK for now):-
```css
.__ns__  button {
    border: 1px solid transparent var(--vp-button-brand-border);
    color: var(--vp-button-brand-text);
    background-color: var(--vp-button-brand-bg);
    border-radius: 20px;
    transition: color .25s, border-color .25s, background-color .25s;
    font-size: 14px;
    font-weight: 600;
    line-height: 38px;
    padding: 0 20px;
    white-space: nowrap;
}

.__ns__  button:hover {
    border-color: var(--vp-button-brand-hover-border);
    background-color: var(--vp-button-brand-hover-bg);
    color: var(--vp-button-brand-hover-text);
    cursor: pointer;
}
```
